### PR TITLE
New pull request to see if testthat package is found now.

### PR DESCRIPTION
**Pull request by matthutchinson1**

### CODE REVIEW

**Comment by tpoisot** [comment]
OK, so `testthat` is found, _but_ there is an issue with the tests themselves -- look at the log here: https://travis-ci.org/PoisotLab/paco/jobs/164429338

**Comment by matthutchinson1** [comment]
Right, I see now. It is strange though. The error is correct in that 'correction' is no longer an argument passed to PACo. But neither of the test scripts have a PACo call where the 'correction' argument is included.

**Comment by matthutchinson1** [comment]
I understand, The Travis build checks the documentation examples as well as the tests. One of the documentation examples is out of date. I will fix this and make a new pull request this afternoon. Thanks for your helps Tim.

**Comment by tpoisot** [comment]
No problem. R is weird.

**Pull request closed without merging**
