### PR TITLE
Documentation changes for R/add_pcoord.r

### PR DESCRIPTION
**Pull request by matthutchinson1**

### CODE REVIEW

**Comment by tpoisot** [comment]
Sweet. And I realize I forgot something: can you use devtools to generate the documentation?

I think the function is call oxygenize or something similar.

Thanks!

**Comment by matthutchinson1** [comment]
Hopefully that's all up-to-date now Tim.

:)

**Comment by tpoisot** [comment]
Perfect! I'm merging right now.

**Comment by efcaguab** [comment]
Does this fixes #2?

**Pull request merged**
